version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    volumes:
      - db_data:/var/lib/postgresql/data

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: example
    volumes:
      - mariadb_data:/var/lib/mysql

  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    restart: always

  flask-api:
    build: ../flask-api
    ports:
      - 5001:5001
    volumes:
      - ../flask-api:/app
    links:
      - nextcloud
    environment:
      - NEXTCLOUD_URL=http://nextcloud
      - NEXTCLOUD_USERNAME=nextcloud
      - NEXTCLOUD_PASSWORD=example

volumes:
  db_data:
  mariadb_data:
  nextcloud:
